### ISSUE TITLE
Compilation fails when trying to set value within newtype wrapper

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/quicklens#132]
given following code:
```scala
tx.modify(_.tokens.value).using(_ * conversionRate)
```

where `tx` is an object that holds value of type `Token` where:
```scala
  @newtype final case class Token(value: BigInt)
```

compilation fails with following error:
```
Unsupported path element. Path must have shape: _.field1.field2.each.field3.(...), got: `package`.this.Token.Ops$newtype(x$2.value)
```

**Comment by KacperFKorban** [comment]
Could you add a `scala-cli`/`scastie` snippet with the full reproduction? (scala version, library versions, etc.)

**Comment by ghostbuster91** [comment]
Yeah, I should've provided all these details right away :sweat_smile: I guess I was in hurry. I am not sure if I will be able to replicate it. Let's close it for now.
