### ISSUE TITLE
How to access index from the same object

### ISSUE THREAD

**Issue by user753** [softwaremill/quicklens#170]
I have this object
```scala
case class Foo(foo: List[Int], idx: Int)
```
How can I create lens like this?
```scala
modifyLens[Foo](_.foo.index(_.idx))
```

**Comment by adamw** [comment]
I'm afraid such constructs are not supported by quicklens - so you'll need to handle this by hand.

**Comment by user753** [comment]
Thanks. Do you mean like this?
```scala
PathLazyModify[Foo, Int]((x, fn) => x.modify(_.foo.index(x.idx)).using(fn))
```

**Comment by adamw** [comment]
Yes, exactly! I'll close this issue since you kind of resolved it yourself :)
