### ISSUE TITLE
1.9.8 regression: copy with different signature than constructor produces error

### ISSUE THREAD

**Issue by OndrejSpanel** [softwaremill/quicklens#256]
Following code fails with a compile error with 1.9.8 and 1.9.9 in Scala 3. It works fine with quicklens 1.9.7 or with Scala 2.

The error is:

> Multiple methods named copy found in Frozen

```scala
import com.softwaremill.quicklens.*

object Main {
  case class Frozen(state: String, ext: Int) {
    def copy(state: String): Frozen = Frozen(state, ext)
  }

  def main(args: Array[String]): Unit = {
    val f = Frozen("A", 0)
    f.modify(_.state).setTo("B")
  }
}
```

My guess is the regression was caused by #236

**Comment by KacperFKorban** [comment]
Hmmm, we might need a heuristic to pick the correct `copy` method. I'll have to check what Scala 2 does.
Should we always choose the synthetic one, if there are multiple alternatives? Or filter by the ones with the desired name first?

**Comment by OndrejSpanel** [comment]
> Should we always choose the synthetic one,

When there is user provided copy, there should be no synthetic one available:

https://www.scala-lang.org/files/archive/spec/3.4/05-classes-and-objects.html?utm_source=chatgpt.com

> A method named `copy` is implicitly added to every case class unless the class already has a member (directly defined or inherited) with that name,

**Comment by KacperFKorban** [comment]
Hmmm, so this looks like a dotty or spec issue, because this compiles:

```scala
//> using scala 3.nightly
//> using dep "com.softwaremill.quicklens::quicklens:1.9.9"
//> using options "-Xprint:typer"

import com.softwaremill.quicklens.*

object Main {
  case class Frozen(state: String, ext: Int) {
    def copy(state: Char): Frozen = Frozen(state.toString, ext)
  }

  def main(args: Array[String]): Unit = {
    val f = Frozen("A", 0)
    // f.modify(_.state).setTo("B")
    f.copy('B')
    f.copy("B", 2)
  }
}
```

Scala-cli one-liner: `scala-cli https://gist.github.com/KacperFKorban/b808cfa80ac20dbb4b85b4d1b6a253a2`

**Comment by OndrejSpanel** [comment]
Interesting. Do you want to post this on scala3, or should I? Meanwhile, picking some particular copy when multiple are available sounds like a good choice. It would be best to mimic what Scala 3 compiler does, but as this seems not to be well specified, picking any should do.

**Comment by KacperFKorban** [comment]
You can post it if it's not a problem :smile:
