### ISSUE TITLE
dotty/scala 3 support

### ISSUE THREAD

**Issue by hamnis** [softwaremill/quicklens#65]
As Scala 3 is getting closer, any plans for supporting it?

**Comment by adamw** [comment]
Probably :) It's going to take a rewrite, though, using the new macros.

Or maybe the new Monocle will provide the same functionality, in that case quicklens could just provide a compatibility layer. Needs investigating :)

**Comment by jatcwang** [comment]
https://youtu.be/oAkiny6BzL0?t=1757

I couldn't find a text / documentation link unfortunately, but I believe monocle 3 already has very similar API.

**Comment by adamw** [comment]
I think the development repo is https://github.com/optics-dev/Monocly

I don't think it's functional yet, though. I tried writing a very basic modify macro using M3 but I bumped into a compiler bug so (already fixed in master) so now I'm waiting for RC1/M4

**Comment by KacperFKorban** [comment]
Hi, are You still planning on rewriting the project?
If so, then I have been experimenting with (re)writing quicklens for Scala 3 [here](https://github.com/KacperFKorban/lightlens).
I'll be happy to share/transfer the code if You think it is adequate enough to serve as a base for Scala 3 implementation of quicklens.

**Comment by adamw** [comment]
@KacperFKorban yes, I am, unfortunately time is hard to stretch ;) But I'll also need a similar macro for tapir so I'll have to get to this anyway.

Of course I'd be happy to either use your code or at least get inspiration from it. If you would like to create a PR (putting the scala3-related code in the `src/main/scala-3` directory, that would be great :)

**Comment by adamw** [comment]
@KacperFKorban Looks great! :) thanks for your work, I'll leave some questions in the code

**Comment by adamw** [comment]
Released in 1.7.0
